version: 0.0
Resources: 
- TargetService:
     Type: AWS::ECS::Service
     Properties:
       TaskDefinition: "arn:aws:ecs:eu-central-1:613950769510:task-definition/AWSCICD-TaskDefinition:1"
       LoadBalancerInfo:
         ContainerName: "awscicd-blue"
         ContainerPort: 8080
