version: 0.0
Resources: 
- TargetService:
     Type: AWS::ECS::Service
     Properties:
       TaskDefinition: "arn:aws:ecs:eu-central-1:794192817635:task-definition/AWScicd-TD:1"
       LoadBalancerInfo:
         ContainerName: "custom-blue"
         ContainerPort: 8080
